/*
Copyright 2025 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package workflowsteps

import (
	"github.com/oam-dev/kubevela/pkg/definition/defkit"
)

// GenerateJDBCConnection creates the generate-jdbc-connection workflow step definition.
// This step generates a JDBC connection based on Component of alibaba-rds.
func GenerateJDBCConnection() *defkit.WorkflowStepDefinition {
	name := defkit.String("name").
		Mandatory().
		Description("Specify the name of the secret generated by database component")
	namespace := defkit.String("namespace").
		Optional().
		Description("Specify the namespace of the secret generated by database component")

	hasNamespace := defkit.PathExists("parameter.namespace")

	return defkit.NewWorkflowStep("generate-jdbc-connection").
		Description("Generate a JDBC connection based on Component of alibaba-rds").
		Category("Terraform").
		WithImports("vela/kube", "vela/util", "encoding/base64").
		Params(name, namespace).
		Template(func(tpl *defkit.WorkflowStepTemplate) {
			tpl.Builtin("output", "kube.#Read").
				WithParams(map[string]defkit.Value{
					"value": defkit.NewArrayElement().
						Set("apiVersion", defkit.Lit("v1")).
						Set("kind", defkit.Lit("Secret")).
						Set("metadata", defkit.NewArrayElement().
							Set("name", name).
							SetIf(hasNamespace, "namespace", namespace),
						),
				}).
				Build()

			tpl.Set("dbHost", defkit.Reference(`util.#ConvertString & {$params: bt: base64.Decode(null, output.$returns.value.data["DB_HOST"])}`))
			tpl.Set("dbPort", defkit.Reference(`util.#ConvertString & {$params: bt: base64.Decode(null, output.$returns.value.data["DB_PORT"])}`))
			tpl.Set("dbName", defkit.Reference(`util.#ConvertString & {$params: bt: base64.Decode(null, output.$returns.value.data["DB_NAME"])}`))
			tpl.Set("username", defkit.Reference(`util.#ConvertString & {$params: bt: base64.Decode(null, output.$returns.value.data["DB_USER"])}`))
			tpl.Set("password", defkit.Reference(`util.#ConvertString & {$params: bt: base64.Decode(null, output.$returns.value.data["DB_PASSWORD"])}`))

			tpl.Set("env", defkit.Reference(`[
	{name: "url", value: "jdbc://" + dbHost.$returns.str + ":" + dbPort.$returns.str + "/" + dbName.$returns.str + "?characterEncoding=utf8&useSSL=false"},
	{name: "username", value: username.$returns.str},
	{name: "password", value: password.$returns.str},
]`))
		})
}

func init() {
	defkit.Register(GenerateJDBCConnection())
}
