name: 'Setup KubeVela Environment'
description: 'Sets up Kubernetes cluster, builds Vela CLI from go.mod replace directive, installs KubeVela, and installs definitions from module'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.23'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Set up Kubernetes (Kind)
      uses: helm/kind-action@v1
      with:
        cluster_name: vela-test
        wait: 120s

    - name: Verify Kubernetes cluster
      shell: bash
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Download and install Vela CLI (latest release)
      shell: bash
      run: |
        curl -fsSl https://kubevela.io/script/install.sh | bash
        vela version

    - name: Install KubeVela
      shell: bash
      run: |
        vela install

    - name: Wait for KubeVela to be ready
      shell: bash
      run: |
        echo "Waiting for KubeVela to be ready..."
        kubectl wait --for=condition=available --timeout=300s deployment/kubevela-vela-core -n vela-system || true
        kubectl get pods -n vela-system

    - name: Extract KubeVela repository info from go.mod
      id: extract-vela-info
      shell: bash
      run: |
        echo "Extracting KubeVela replace directive from go.mod..."
        
        # Extract the replace line for github.com/oam-dev/kubevela
        REPLACE_LINE=$(grep "replace github.com/oam-dev/kubevela =>" go.mod || true)
        
        if [ -z "$REPLACE_LINE" ]; then
          echo "No replace directive found for kubevela, using default"
          echo "repository=oam-dev/kubevela" >> $GITHUB_OUTPUT
          echo "ref=master" >> $GITHUB_OUTPUT
        else
          echo "Found replace directive: $REPLACE_LINE"
          
          # Extract the replacement module path and version
          # Format: replace github.com/oam-dev/kubevela => github.com/user/repo v0.0.0-YYYYMMDDHHMMSS-commitsha
          REPLACEMENT=$(echo "$REPLACE_LINE" | sed 's/.*=> //')
          
          # Extract repository (github.com/user/repo -> user/repo)
          REPO=$(echo "$REPLACEMENT" | awk '{print $1}' | sed 's|github.com/||')
          
          # Extract version string
          VERSION=$(echo "$REPLACEMENT" | awk '{print $2}')
          
          # Extract commit SHA from pseudo-version (v0.0.0-YYYYMMDDHHMMSS-commitsha)
          # The commit SHA is the last part after the last hyphen (12 chars, but git can resolve it)
          COMMIT_SHA=$(echo "$VERSION" | sed 's/.*-//')
          
          echo "Extracted repository: $REPO"
          echo "Extracted version: $VERSION"
          echo "Extracted commit SHA: $COMMIT_SHA"
          
          echo "repository=$REPO" >> $GITHUB_OUTPUT
          echo "ref=$COMMIT_SHA" >> $GITHUB_OUTPUT
        fi

    - name: Clone KubeVela repository and checkout commit
      shell: bash
      run: |
        REPO="${{ steps.extract-vela-info.outputs.repository }}"
        REF="${{ steps.extract-vela-info.outputs.ref }}"
        
        echo "Cloning repository: $REPO"
        echo "Target ref: $REF"
        
        # Clone the full repository (needed to checkout specific commits)
        git clone "https://github.com/${REPO}.git" kubevela-source
        cd kubevela-source
        
        # Checkout the specific commit or branch
        git checkout "$REF"
        
        echo "Checkout complete"
        git log -1 --oneline

    - name: Verify cloned repository
      shell: bash
      working-directory: kubevela-source
      run: |
        echo "Repository: ${{ steps.extract-vela-info.outputs.repository }}"
        echo "Ref: ${{ steps.extract-vela-info.outputs.ref }}"
        echo "Current commit:"
        git log -1 --oneline
        echo "Working directory contents:"
        ls -la

    - name: Build Vela CLI from source
      shell: bash
      working-directory: kubevela-source
      run: |
        echo "Building Vela CLI..."
        make vela-cli

    - name: Verify built CLI
      shell: bash
      working-directory: kubevela-source
      run: |
        if [ -f bin/vela ]; then
          echo "Vela CLI built successfully!"
          ./bin/vela version
          ls -lh bin/vela
        else
          echo "Error: Vela CLI binary not found in bin/vela"
          find . -name "vela" -type f
          exit 1
        fi

    - name: Uninstall built-in definitions
      shell: bash
      run: |
        echo "Uninstalling built-in component definitions..."
        kubectl delete componentdefinitions --all -n vela-system || true
        kubectl delete traitdefinitions --all -n vela-system || true
        kubectl delete workflowstepdefinitions --all -n vela-system || true
        kubectl delete policydefinitions --all -n vela-system || true
        echo "Built-in definitions uninstalled"

    - name: Prepare Go module dependencies
      shell: bash
      run: |
        echo "Running make tidy..."
        make tidy
        echo "Go dependencies updated"

    - name: List definitions from vela-definitions module
      shell: bash
      run: |
        echo "Listing definitions from vela-definitions module..."
        kubevela-source/bin/vela def list-module .

    - name: Install definitions from defkit
      shell: bash
      run: |
        echo "Installing definitions from vela-definitions module..."
        kubevela-source/bin/vela def apply-module . --conflict=overwrite
        echo "Definitions installed successfully"

    - name: Verify installed definitions
      shell: bash
      run: |
        echo "Verifying installed definitions..."
        kubectl get componentdefinitions -n vela-system
        kubectl get traitdefinitions -n vela-system
        kubectl get workflowstepdefinitions -n vela-system
        kubectl get policydefinitions -n vela-system

    - name: Install Ginkgo
      shell: bash
      run: |
        make install-ginkgo
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

